### ISSUE TITLE
How to Automatically merge the generated contents to the current document?

### ISSUE THREAD

**Issue by iceCream001** [Helixform/CodeCursor#13]
just like the changelog said in version 0.2.1

**Comment by unixzii** [comment]
Automatic merging refers to applying the changes (by AI) to the current document with automatic reconciliation. It's like how Git is working. Let's say you made AI to make some changes, at the meantime, you edited the original document. Later, when you accept the change, instead of replacing the original selection with the AI generated contents, the extension finds out the exact changes that AI made, and applies them to your current version document.

To to simplified, this feature allows you continuing your works without waiting for AI to generate contents.
